<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />


<meta name="author" content="Witek ten Hove" />


<title>R-Workshop</title>

<script src="index_files/jquery-1.11.3/jquery.min.js"></script>
<script src="index_files/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="index_files/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="index_files/tocify-1.9.1/jquery.tocify.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="index_files/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="index_files/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="index_files/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="index_files/bootstrap-3.3.5/shim/respond.min.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<link rel="stylesheet"
      href="index_files/highlight/default.css"
      type="text/css" />
<script src="index_files/highlight/highlight.js"></script>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs && document.readyState && document.readyState === "complete") {
   window.setTimeout(function() {
      hljs.initHighlighting();
   }, 0);
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>


<div class="container-fluid main-container">

<!-- tabsets -->
<script src="index_files/navigation-1.0/tabsets.js"></script>
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->
<script src="index_files/navigation-1.0/codefolding.js"></script>
<script>
$(document).ready(function () {
  window.initializeCodeFolding("show" === "show");
});
</script>




<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.9em;
  padding-left: 5px;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>

<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="fluid-row" id="header">

<div class="btn-group pull-right">
<button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All</a></li>
</ul>
</div>


<h1 class="title toc-ignore">R-Workshop</h1>
<h4 class="author"><em>Witek ten Hove</em></h4>
<h4 class="date"><em>11 August, 2016</em></h4>

</div>


<script src="//maps.googleapis.com/maps/api/js?key=AIzaSyAfbzoFaFxwmdLDpzlwjku5kCcSgPLb33I" async="" defer="defer" type="text/javascript"></script>
<div id="inleiding" class="section level1">
<h1>Inleiding</h1>
<p>In deze workshop leer je op een slimme wijze kwantitatieve data verzamelen, deze om te zetten naar bruikbare input voor je analyse en uitkomsten te visualiseren en te rapporteren.</p>
<p>Tijdens de workshop werk je met R. Deze software is speciaal ontwikkeld om makkelijk en snel data in te lezen en te verwerken. Het is op dit moment naast Python de belangrijkste tool voor data analyse en wordt ingezet door ondernemingen als bijvoorbeeld Facebook, Airbnb en Microsoft om informatie uit hun enorme databestanden te genereren. Je bent dus in uitstekend gezelschap als je klaar bent met het leertraject.</p>
<p>Deze workshop is ontwikkeld voor mensen die nog geen of zeer beperkte ervaring hebben met programmeren. Wellicht heb je al een beetje ervaring met Excel of SPSS. Dit is handig, maar geen vereiste om deel te kunnen nemen. R is een programmeertaal, maar zeer eenvoudig qua opzet en je zult merken dat je al heel snel krachtige stukjes code (scripts) kunt schrijven. Je hoeft geen investeringen te doen, want R is volledig open source en werkt op zowel Mac OS, Windows als Linux.</p>
<div id="workshop-sessies" class="section level2">
<h2>Workshop sessies</h2>
<p>De workshop bestaat uit drie sessies:</p>
<ul>
<li><strong>Sessie 1</strong>: Dinsdag 6 september 2016 van 18:30 tot 21:00u</li>
<li><strong>Sessie 2</strong>: Dinsdag 13 september 2016 van 18:30 tot 21:00u</li>
<li><strong>Sessie 3</strong>: Dinsdag 20 september 2016 van 18:30 tot 21:00u</li>
</ul>
<p>Locatie: HAN, Kapittelweg 33, 6525 EN Nijmegen (Lokaal C106)</p>
<!-- Map generated in R 3.3.0 by googleVis 0.5.10 package -->
<!-- Thu Aug 11 12:57:10 2016 -->
<!-- jsHeader -->
<script type="text/javascript">
 
// jsData 
function gvisDataMapID41af78f6b46c () {
var data = new google.visualization.DataTable();
var datajson =
[
 [
 "HAN, Kapittelweg 33, 6525 EN Nijmegen",
"Lokaal C106<br><a href='https://goo.gl/maps/PA9xeFzKYNp'>Get directions</a>" 
] 
];
data.addColumn('string','adres');
data.addColumn('string','tooltip');
data.addRows(datajson);
return(data);
}
 
// jsDrawChart
function drawChartMapID41af78f6b46c() {
var data = gvisDataMapID41af78f6b46c();
var options = {};
options["showTip"] = true;
options["mapType"] = "normal";
options["zoomLevel"] =     16;
options["width"] =    100;
options["height"] =    300;

    var chart = new google.visualization.Map(
    document.getElementById('MapID41af78f6b46c')
    );
    chart.draw(data,options);
    

}
  
 
// jsDisplayChart
(function() {
var pkgs = window.__gvisPackages = window.__gvisPackages || [];
var callbacks = window.__gvisCallbacks = window.__gvisCallbacks || [];
var chartid = "map";
  
// Manually see if chartid is in pkgs (not all browsers support Array.indexOf)
var i, newPackage = true;
for (i = 0; newPackage && i < pkgs.length; i++) {
if (pkgs[i] === chartid)
newPackage = false;
}
if (newPackage)
  pkgs.push(chartid);
  
// Add the drawChart function to the global list of callbacks
callbacks.push(drawChartMapID41af78f6b46c);
})();
function displayChartMapID41af78f6b46c() {
  var pkgs = window.__gvisPackages = window.__gvisPackages || [];
  var callbacks = window.__gvisCallbacks = window.__gvisCallbacks || [];
  window.clearTimeout(window.__gvisLoad);
  // The timeout is set to 100 because otherwise the container div we are
  // targeting might not be part of the document yet
  window.__gvisLoad = setTimeout(function() {
  var pkgCount = pkgs.length;
  google.load("visualization", "1", { packages:pkgs, callback: function() {
  if (pkgCount != pkgs.length) {
  // Race condition where another setTimeout call snuck in after us; if
  // that call added a package, we must not shift its callback
  return;
}
while (callbacks.length > 0)
callbacks.shift()();
} });
}, 100);
}
 
// jsFooter
</script>
<!-- jsChart -->
<script type="text/javascript" src="https://www.google.com/jsapi?callback=displayChartMapID41af78f6b46c"></script>
<!-- divChart -->
<div id="MapID41af78f6b46c" style="width: 100; height: 300;">

</div>
<p><br> Tijdens iedere sessie ga je werken aan een opdracht. Je krijgt een dataset (of een verwijzing naar een online databron) en gaat hier informatie uit halen. De instructeur helpt je als je vastloopt of geeft suggesties voor verbeteringen van je code.</p>
</div>
<div id="inschrijving" class="section level2">
<h2>Inschrijving</h2>
<p>Aanmelding geschiedt via dit formulier. Er kunnen maximaal 16 personen deelnemen. Mocht er na de aanmelding iets veranderd zijn waardoor je niet meer kunt deelnemen, geef dit dan door aan de instructeur.</p>
<p>Inschrijving vindt plaats naar volgorde van aanmelding. Nadat de aanmeldingstermijn is verstreken, zullen de deelnemers per mail worden geinformeerd.</p>
<p>De kosten van de workshop bedragen 30 EUR per persoon. Het bedrag zal tijdens de eerste sessie contant worden afgerekend met de instructeur.</p>
</div>
<div id="voorbereiding" class="section level2">
<h2>Voorbereiding</h2>
<p>Download R en RStudio. Install.packages(c(“gsheet”, “rvest”, “quandmod”, “dplyr”, “googleVis”, “plotly”, “leaflet”))</p>
</div>
<div id="basis" class="section level2">
<h2>Basis</h2>
<p>In RStudio kun je op twee manieren code schrijven en laten uitvoeren:</p>
<ul>
<li>Direct via de console</li>
<li>Indirect via een script</li>
</ul>
<p>Meestal zul je eerst je code in een script schrijven en als je helemaal tevreden bent, uitvoeren. Het voordeel is tevens dat je een script kunt bewaren.</p>
<p>Maak een nieuw R Script aan in RStudio via het icoontje met het groene plusje:</p>
<div class="figure">
<img src="images/newfile.png" alt=" of File &gt;&gt; New File &gt;&gt; R Script" />
<p class="caption"><br>of <em>File &gt;&gt; New File &gt;&gt; R Script</em></p>
</div>
<p>Er wordt nu een venster met een veld voor tekstbewerking geopend. Je kunt hier je instructies invoeren, bijvoorbeeld een optelling.</p>
<div class="figure">
<img src="images/editor.png" alt="" />

</div>
<p><br></p>
<p>Selecteer alles en klik op <em>Run</em>:</p>
<div class="figure">
<img src="images/run.png" alt=" of Ctrl + Enter" />
<p class="caption"><br>of <em>Ctrl + Enter</em></p>
</div>
<p>In de console zie je het resultaat.</p>
<pre><code>## [1] 5</code></pre>
<p>We hebben nu niet meer gedaan dan je ook op een gewone rekenmachine kunt uitvoeren. R is echter geen rekenmachine, maar een programmeertaal. In iedere programmeertaal kun je gegevens in variabelen opslaan en deze variabelen hergebruiken.</p>
<p>We kunnen bijvoorbeeld een variabele <em>a</em> en <em>b</em> aanmaken en daarin de waarden <em>2</em> en <em>3</em> bewaren. Het resultaat van de optelling bewaren we in een variabele <em>c</em>.</p>
<pre class="r"><code>a &lt;- 2
b &lt;- 3
c &lt;- a + b
c</code></pre>
<pre><code>## [1] 5</code></pre>
<p>Het voordeel hiervan is dat we nu <em>a</em> of <em>b</em> andere waarden kunnen geven en dat de waarde van <em>c</em> automatisch wordt aangepast.</p>
<pre class="r"><code>a &lt;- 4
b &lt;- 3
c &lt;- a + b
c</code></pre>
<pre><code>## [1] 7</code></pre>
<p>Om goed te kunnen begrijpen hoe R werkt, is het belangrijk bekend te raken met een aantal basiselementen, <code>classes</code>, <code>vectors</code> en <code>data frames</code>, en te begrijpen hoe deze elementen zich tot elkaar verhouden.</p>
<p>De belangrijkste datatypes (<code>classes</code>) binnen R zijn: getallen, letters en factoren. Een vector is een geordende verzameling van elementen van hetzelfde type data.</p>
<p>Bijvoorbeeld de vector: <code>(&quot;Warszawa&quot;, &quot;London&quot;, &quot;Paris&quot;)</code> is een vector van plaatsen en de elementen zijn van <code>class</code> letters (<code>character</code>). De elementen uit de vector <code>(&quot;Man&quot;, &quot;Man&quot;, &quot;Vrouw&quot;)</code> kunnen van <code>class</code> letters zijn, maar waarschijnlijk is de functie van zo een vector een verzameling van factoren met 2 levels: <code>Man</code> en <code>Vrouw</code>. Dit kunnen we specifiek aangeven in R.</p>
<pre class="r"><code>## Vectoren en classes
Plaats &lt;- c(&quot;Warszawa&quot;, &quot;London&quot;, &quot;Paris&quot;)
class(Plaats)</code></pre>
<pre><code>## [1] &quot;character&quot;</code></pre>
<pre class="r"><code>Geslacht &lt;- c(&quot;Man&quot;, &quot;Man&quot;, &quot;Vrouw&quot;)
class(Geslacht)</code></pre>
<pre><code>## [1] &quot;character&quot;</code></pre>
<pre class="r"><code>Geslacht &lt;- as.factor(Geslacht)
class(Geslacht)</code></pre>
<pre><code>## [1] &quot;factor&quot;</code></pre>
<p>Ieder element binnen een vector heeft een indexnummer beginnend bij 1. Als we de vector <code>(&quot;Warszawa&quot;, &quot;London&quot;, &quot;Paris&quot;)</code> de naam <code>Plaats</code> geven dan heeft het element <code>Plaats[2]</code> de waarde <code>&quot;London&quot;</code>.</p>
<pre class="r"><code>## Vectorindices
Plaats[2]</code></pre>
<pre><code>## [1] &quot;London&quot;</code></pre>
<p>We kunnen met behulp van indexnummers elementen toevoegen of verwijderen.</p>
<pre class="r"><code>## Vectorelementen toevoegen of verwijderen.
Plaats[4] &lt;- &quot;Amsterdam&quot;
Plaats</code></pre>
<pre><code>## [1] &quot;Warszawa&quot;  &quot;London&quot;    &quot;Paris&quot;     &quot;Amsterdam&quot;</code></pre>
<pre class="r"><code>Plaats &lt;- Plaats[-3]
Plaats</code></pre>
<pre><code>## [1] &quot;Warszawa&quot;  &quot;London&quot;    &quot;Amsterdam&quot;</code></pre>
<p>Stel we creëren een tweede vector <code>Land</code> met de elementen <code>(&quot;Polska&quot;, &quot;UK&quot;, &quot;Nederland&quot;)</code>. We kunnen nu de vectoren <code>Plaats</code> en <code>Land</code> samenvoegen in een data frame en via de indexen <em>[rij,kolom]</em> de elementen opvragen.</p>
<pre class="r"><code>## Data frame structuur
Land &lt;- c(&quot;Polska&quot;, &quot;UK&quot;, &quot;Nederland&quot;)
Locatie &lt;- data.frame(Plaats, Land)
Locatie</code></pre>
<pre><code>##      Plaats      Land
## 1  Warszawa    Polska
## 2    London        UK
## 3 Amsterdam Nederland</code></pre>
<pre class="r"><code>Locatie[3,1]</code></pre>
<pre><code>## [1] Amsterdam
## Levels: Amsterdam London Warszawa</code></pre>
<pre class="r"><code>Locatie[3,]</code></pre>
<pre><code>##      Plaats      Land
## 3 Amsterdam Nederland</code></pre>
<pre class="r"><code>Locatie[,2]</code></pre>
<pre><code>## [1] Polska    UK        Nederland
## Levels: Nederland Polska UK</code></pre>
<p>We kunnen ook de afzonderlijke variabelen binnen een data frame oproepen via het <code>$</code> teken.</p>
<pre class="r"><code>## Data frame structuur
Locatie$Land</code></pre>
<pre><code>## [1] Polska    UK        Nederland
## Levels: Nederland Polska UK</code></pre>
<pre class="r"><code>Locatie$Plaats[1]</code></pre>
<pre><code>## [1] Warszawa
## Levels: Amsterdam London Warszawa</code></pre>
<div id="vragenset-basis" class="section level3">
<h3>Vragenset Basis</h3>
<ol style="list-style-type: decimal">
<li><p>Zoals je ziet hebben de variabelen <code>Plaats</code> en <code>Land</code> uit het voorbeeld door de omzetting naar een data frame de <code>class</code> <code>factor</code> gekregen. Hoe zet je de <code>class</code> van beide variabelen weer terug naar <code>character</code>?</p></li>
<li><p>Hoe vervang je de elementen uit de laatste rij door <code>(&quot;Berlin&quot;, &quot;Deutschland&quot;)</code>?</p></li>
</ol>
</div>
</div>
<div id="naslagwerk" class="section level2">
<h2>Naslagwerk</h2>
<p>Literatuur</p>
<p>Internet</p>
<hr />
</div>
</div>
<div id="sessie-1---inlezen-bekijken" class="section level1">
<h1>Sessie 1 - Inlezen / Bekijken</h1>
<p>In deze sessie gaan we kijken hoe je data uit verschillende bronnen kunt inlezen. We beginnen eenvoudig en lezen een lokaal opgeslagen bestand uit. Daarna gaan we data uitlezen vanuit een online spreadsheet. We eindigen met het scrapen van informatie uit een webpagina.</p>
<div id="lokaal-bestand" class="section level2">
<h2>Lokaal bestand</h2>
<p>Maak een nieuw R Script aan in RStudio en bewaar het in een voor jou logische folder op je computer (geef het een zinvolle naam, bijvoorbeeld <code>readSessie1.R</code>). Verwijs in RStudio naar deze werkfolder door te klikken op <em>Session &gt;&gt; Set Working Directory &gt;&gt; To Source File Location</em></p>
<p>Download nu het volgende bestand: <a href="https://github.com/witusj/R-workshop/raw/gh-pages/datasets/sessie%201/stud_perf.csv" download>Student Performance (csv)</a> en sla het op in de werkfolder. Nu ben je klaar om je eerste data in te lezen in R.</p>
<p>In het scriptvenster in RStudio schrijf (of kopieer) je volgende instructie:</p>
<pre class="r"><code>## Lees data uit lokaal csv-bestand
studDF &lt;- read.csv(&quot;stud_perf.csv&quot;, stringsAsFactors = FALSE)</code></pre>
<p>Selecteer alles en klik op Run. In de console van RStudio zie je dat de instructies worden uitgevoerd, maar je ziet verder geen resultaten. R heeft echter alle data in het geheugen geladen. Je kunt dit zien in het <em>Environment</em> veld waar nu een data object <em>studDF</em> is toegevoegd:</p>
<div class="figure">
<img src="images/env.png" alt="" />

</div>
<p><br> We kunnen snel controleren of de data goed is overgekomen door naar de eerste zes rijen te kijken:</p>
<pre class="r"><code>## Bekijk eerste regels van data
head(studDF)</code></pre>
<pre><code>##       Voor      Achter Kennistoetsen Schriftelijk Schriftelijk.Voldoende
## 1    ANTON   Entwistle           0.0          6.0                    100
## 2 CHRISTEN    Hardaway           4.6          2.2                      0
## 3    KYLEE      Mauzey           5.3          8.8                    100
## 4      KAI    Tredwell           5.0          4.8                      0
## 5     NELL      Darden           6.7          9.2                    100
## 6  KIRSTIE Tinklenberg           7.7          7.4                    100
##   Schriftelijk.Bonus Schriftelijk.Bonus.Voldoende Clicks Weblectures
## 1                6.0                          100    536         5.5
## 2                2.2                            0    636         0.8
## 3                8.8                          100    666         3.6
## 4                4.8                            0    479         1.2
## 5               10.0                          100    298         0.0
## 6                8.6                          100    863         0.0
##   BEC.Propedeuse AEC.Propedeuse Vooropleiding
## 1              1              1          HAVO
## 2              0              0           MBO
## 3              1              1           MBO
## 4              1              1          HAVO
## 5              1              1          HAVO
## 6              1              1           MBO</code></pre>
<p><br> Het gaat hier klaarblijkelijk om een cijferlijst van studenten. Alles lijkt correct te zijn ingelezen door R en we kunnen nu wat nauwkeuriger kijken naar de data. Het is een goede gewoonte om eerst de structuur van de data te onderzoeken:</p>
<pre class="r"><code>## Bekijk de structuur van data
str(studDF)</code></pre>
<pre><code>## &#39;data.frame&#39;:    109 obs. of  12 variables:
##  $ Voor                        : chr  &quot;ANTON&quot; &quot;CHRISTEN&quot; &quot;KYLEE&quot; &quot;KAI&quot; ...
##  $ Achter                      : chr  &quot;Entwistle&quot; &quot;Hardaway&quot; &quot;Mauzey&quot; &quot;Tredwell&quot; ...
##  $ Kennistoetsen               : num  0 4.6 5.3 5 6.7 7.7 3.8 4.8 4.5 4.1 ...
##  $ Schriftelijk                : num  6 2.2 8.8 4.8 9.2 7.4 5 5.8 3.2 6.6 ...
##  $ Schriftelijk.Voldoende      : int  100 0 100 0 100 100 0 100 0 100 ...
##  $ Schriftelijk.Bonus          : num  6 2.2 8.8 4.8 10 8.6 5 5.8 3.2 6.6 ...
##  $ Schriftelijk.Bonus.Voldoende: int  100 0 100 0 100 100 0 100 0 100 ...
##  $ Clicks                      : int  536 636 666 479 298 863 434 428 441 1058 ...
##  $ Weblectures                 : num  5.5 0.8 3.6 1.2 0 0 0 0 0 1.2 ...
##  $ BEC.Propedeuse              : int  1 0 1 1 1 1 1 0 0 1 ...
##  $ AEC.Propedeuse              : int  1 0 1 1 1 1 1 1 0 1 ...
##  $ Vooropleiding               : chr  &quot;HAVO&quot; &quot;MBO&quot; &quot;MBO&quot; &quot;HAVO&quot; ...</code></pre>
<p><br> en we zien dat de data de vorm van een data frame (tabel) heeft met 109 rijen (observaties) en 12 kolommen (variabelen). De eerste variabele heet <code>Voor</code> en de elementen bestaan uit letters (<code>chr</code>). De derde variabele heet <code>Kennistoetsen</code> en de elementen zijn getallen (<code>num</code>). De vijfde variabele heet <code>Schriftelijk.Voldoende</code> en bestaat uit gehele getallen (<code>int</code>).</p>
<p>Met <code>summary()</code> kunnen we de kwaliteit van de data beoordelen:</p>
<pre class="r"><code>## Bekijk de kwaliteit van data
summary(studDF)</code></pre>
<pre><code>##      Voor              Achter          Kennistoetsen   Schriftelijk  
##  Length:109         Length:109         Min.   :0.00   Min.   :0.800  
##  Class :character   Class :character   1st Qu.:3.20   1st Qu.:4.000  
##  Mode  :character   Mode  :character   Median :4.80   Median :5.600  
##                                        Mean   :4.48   Mean   :5.503  
##                                        3rd Qu.:5.70   3rd Qu.:6.800  
##                                        Max.   :8.30   Max.   :9.600  
##                                                                      
##  Schriftelijk.Voldoende Schriftelijk.Bonus Schriftelijk.Bonus.Voldoende
##  Min.   :  0.00         Min.   : 0.800     Min.   :  0.00              
##  1st Qu.:  0.00         1st Qu.: 4.000     1st Qu.:  0.00              
##  Median :100.00         Median : 5.600     Median :100.00              
##  Mean   : 52.29         Mean   : 5.787     Mean   : 53.21              
##  3rd Qu.:100.00         3rd Qu.: 7.600     3rd Qu.:100.00              
##  Max.   :100.00         Max.   :10.000     Max.   :100.00              
##                                                                        
##      Clicks        Weblectures     BEC.Propedeuse  AEC.Propedeuse  
##  Min.   :   1.0   Min.   :0.0000   Min.   :0.000   Min.   :0.0000  
##  1st Qu.: 269.0   1st Qu.:0.0000   1st Qu.:1.000   1st Qu.:1.0000  
##  Median : 386.0   Median :0.0000   Median :1.000   Median :1.0000  
##  Mean   : 445.7   Mean   :0.8505   Mean   :0.875   Mean   :0.9327  
##  3rd Qu.: 541.0   3rd Qu.:1.2000   3rd Qu.:1.000   3rd Qu.:1.0000  
##  Max.   :1058.0   Max.   :6.8000   Max.   :1.000   Max.   :1.0000  
##                                    NA&#39;s   :5       NA&#39;s   :5       
##  Vooropleiding     
##  Length:109        
##  Class :character  
##  Mode  :character  
##                    
##                    
##                    
## </code></pre>
<p><br> We kunnen hieruit onder andere aflezen dat de gemiddelde score van de kennistoetsen 4.48 bedroeg met een maximum van 8.3 en dat bij de variabele <code>BEC.Propedeuse</code> van 5 observaties de gegevens ontbreken (<code>NA</code>).</p>
<div id="vragenset-1" class="section level3">
<h3>Vragenset 1</h3>
<ol style="list-style-type: decimal">
<li><p>Hoeveel procent van de studenten heeft voor het schriftelijk tentamen (inclusief bonuspunten) een voldoende gehaald?</p></li>
<li><p>In hoeveel procent van de gevallen hadden studenten de bonuspunten nodig om voor het schriftelijk een voldoende te halen?</p></li>
</ol>
</div>
</div>
<div id="online-bestand" class="section level2">
<h2>Online bestand</h2>
<p><code>gsheet</code></p>
</div>
<div id="web-scraping" class="section level2">
<h2>Web scraping</h2>
<p><code>rvest</code> en <code>quandmod</code></p>
<hr />
</div>
</div>
<div id="sessie-2---muteren-analyseren" class="section level1">
<h1>Sessie 2 - Muteren / Analyseren</h1>
<p>In deze sessie gaan we de kwaliteit van de ruwe data bekijken en leren we hoe je met slimme tools data kunt aanpassen, zodat deze gebruikt kan worden voor verdere analyse of visualisatie.</p>
<div id="muteren" class="section level2">
<h2>Muteren</h2>
<p>Met de package <code>dplyr</code> kan data eenvoudig worden aangepast. Installeer <code>dplyr</code> via de ‘Install’ knop in Rstudio of via het commando:</p>
<pre class="r"><code>install.packages(&quot;dplyr&quot;)</code></pre>
</div>
<div id="analyseren" class="section level2">
<h2>Analyseren</h2>
<p><code>table()</code>, <code>plot()</code> en <code>hist()</code></p>
<hr />
</div>
</div>
<div id="sessie-3---visualiseren-presenteren" class="section level1">
<h1>Sessie 3 - Visualiseren / Presenteren</h1>
<p>In deze sessie kijken we hoe je data visueel kunt opmaken en op een makkelijke manier toegankelijk maakt voor de gebruikers.</p>
<div id="visualiseren" class="section level2">
<h2>Visualiseren</h2>
<p><code>googleVis</code>, <code>plotly</code> en <code>leaflet</code></p>
</div>
<div id="presenteren." class="section level2">
<h2>Presenteren.</h2>
<p><em>markdown</em> en <em>RPubs</em></p>
<hr />
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
$(document).ready(function () {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
});

</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
