<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />


<meta name="author" content="Witek ten Hove - wfth1969@gmail.com" />


<title>R-Workshop</title>

<script src="index_files/jquery-1.11.3/jquery.min.js"></script>
<script src="index_files/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="index_files/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="index_files/tocify-1.9.1/jquery.tocify.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="index_files/bootstrap-3.3.5/css/cerulean.min.css" rel="stylesheet" />
<script src="index_files/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="index_files/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="index_files/bootstrap-3.3.5/shim/respond.min.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<link rel="stylesheet"
      href="index_files/highlight/default.css"
      type="text/css" />
<script src="index_files/highlight/highlight.js"></script>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs && document.readyState && document.readyState === "complete") {
   window.setTimeout(function() {
      hljs.initHighlighting();
   }, 0);
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>


<div class="container-fluid main-container">

<!-- tabsets -->
<script src="index_files/navigation-1.1/tabsets.js"></script>
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->
<script src="index_files/navigation-1.1/codefolding.js"></script>
<script>
$(document).ready(function () {
  window.initializeCodeFolding("show" === "show");
});
</script>




<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}


.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.9em;
  padding-left: 5px;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>

<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="fluid-row" id="header">

<div class="btn-group pull-right">
<button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">R-Workshop</h1>
<h4 class="author"><em>Witek ten Hove - <a href="mailto:wfth1969@gmail.com">wfth1969@gmail.com</a></em></h4>
<h4 class="date"><em>10 September, 2016</em></h4>

</div>


<div id="sessie-1---inlezen-bekijken" class="section level1">
<h1>Sessie 1 - Inlezen / Bekijken</h1>
<p>In deze sessie gaan we kijken hoe je data uit verschillende bronnen kunt inlezen. We beginnen eenvoudig en lezen een lokaal opgeslagen bestand uit. Daarna gaan we data uitlezen vanuit een online spreadsheet. We eindigen met het scrapen van informatie uit een webpagina.</p>
<div id="lokaal-bestand" class="section level2">
<h2>Lokaal bestand</h2>
<p>Maak een nieuw R Script aan in RStudio en bewaar het in een voor jou logische folder op je computer (geef het een zinvolle naam, bijvoorbeeld <code>werkSessie1.R</code>). Verwijs in RStudio naar deze werkfolder door te klikken op <em>Session &gt;&gt; Set Working Directory &gt;&gt; To Source File Location</em></p>
<p>Download nu het volgende databestand: <a href="https://github.com/witusj/R-workshop/raw/gh-pages/datasets/sessie%201/stud_perf.csv" download>Student Performance (csv)</a> en sla het op in de werkfolder. Nu ben je klaar om je eerste data in te lezen in R.</p>
<p>In het scriptvenster in RStudio schrijf (of kopieer) je volgende instructie:</p>
<pre class="r"><code>## Lees data uit lokaal csv-bestand
studDF &lt;- read.csv(&quot;stud_perf.csv&quot;, stringsAsFactors = FALSE)</code></pre>
<p>Selecteer alles en klik op Run. In de console van RStudio zie je dat de instructies worden uitgevoerd, maar je ziet verder geen resultaten. R heeft echter alle data in het geheugen geladen. Je kunt dit zien in het <em>Environment</em> veld waar nu een data object <em>studDF</em> is toegevoegd:</p>
<div class="figure">
<img src="images/env.png" alt="" />

</div>
<p><br> We kunnen snel controleren of de data goed is overgekomen door naar de eerste zes rijen te kijken:</p>
<pre class="r"><code>## Bekijk eerste regels van data
head(studDF)</code></pre>
<pre><code>##       Voor      Achter Kennistoetsen Schriftelijk Schriftelijk.Voldoende
## 1    ANTON   Entwistle           0.0          6.0                    100
## 2 CHRISTEN    Hardaway           4.6          2.2                      0
## 3    KYLEE      Mauzey           5.3          8.8                    100
## 4      KAI    Tredwell           5.0          4.8                      0
## 5     NELL      Darden           6.7          9.2                    100
## 6  KIRSTIE Tinklenberg           7.7          7.4                    100
##   Schriftelijk.Bonus Schriftelijk.Bonus.Voldoende Clicks Weblectures
## 1                6.0                          100    536         5.5
## 2                2.2                            0    636         0.8
## 3                8.8                          100    666         3.6
## 4                4.8                            0    479         1.2
## 5               10.0                          100    298         0.0
## 6                8.6                          100    863         0.0
##   BEC.Propedeuse AEC.Propedeuse Vooropleiding
## 1              1              1          HAVO
## 2              0              0           MBO
## 3              1              1           MBO
## 4              1              1          HAVO
## 5              1              1          HAVO
## 6              1              1           MBO</code></pre>
<p><br> Het gaat hier klaarblijkelijk om een cijferlijst van studenten met wat metadata. Alles lijkt correct te zijn ingelezen door R en we kunnen nu wat nauwkeuriger kijken naar de data. Het is een goede gewoonte om eerst de structuur van de data te onderzoeken:</p>
<pre class="r"><code>## Bekijk de structuur van data
str(studDF)</code></pre>
<pre><code>## &#39;data.frame&#39;:    109 obs. of  12 variables:
##  $ Voor                        : chr  &quot;ANTON&quot; &quot;CHRISTEN&quot; &quot;KYLEE&quot; &quot;KAI&quot; ...
##  $ Achter                      : chr  &quot;Entwistle&quot; &quot;Hardaway&quot; &quot;Mauzey&quot; &quot;Tredwell&quot; ...
##  $ Kennistoetsen               : num  0 4.6 5.3 5 6.7 7.7 3.8 4.8 4.5 4.1 ...
##  $ Schriftelijk                : num  6 2.2 8.8 4.8 9.2 7.4 5 5.8 3.2 6.6 ...
##  $ Schriftelijk.Voldoende      : int  100 0 100 0 100 100 0 100 0 100 ...
##  $ Schriftelijk.Bonus          : num  6 2.2 8.8 4.8 10 8.6 5 5.8 3.2 6.6 ...
##  $ Schriftelijk.Bonus.Voldoende: int  100 0 100 0 100 100 0 100 0 100 ...
##  $ Clicks                      : int  536 636 666 479 298 863 434 428 441 1058 ...
##  $ Weblectures                 : num  5.5 0.8 3.6 1.2 0 0 0 0 0 1.2 ...
##  $ BEC.Propedeuse              : int  1 0 1 1 1 1 1 0 0 1 ...
##  $ AEC.Propedeuse              : int  1 0 1 1 1 1 1 1 0 1 ...
##  $ Vooropleiding               : chr  &quot;HAVO&quot; &quot;MBO&quot; &quot;MBO&quot; &quot;HAVO&quot; ...</code></pre>
<p><br> en we zien dat de data de vorm van een <em>data frame</em> (tabel) heeft met 109 rijen (observaties) en 12 kolommen (variabelen). De eerste variabele heet <code>Voor</code> en de elementen bestaan uit letters (<code>chr</code>). De derde variabele heet <code>Kennistoetsen</code> en de elementen zijn getallen (<code>num</code>). De vijfde variabele heet <code>Schriftelijk.Voldoende</code> en bestaat uit gehele getallen (<code>int</code>).</p>
<p>Met <code>summary()</code> kunnen we de kwaliteit van de data beoordelen:</p>
<pre class="r"><code>## Bekijk de kwaliteit van data
summary(studDF)</code></pre>
<pre><code>##      Voor              Achter          Kennistoetsen   Schriftelijk  
##  Length:109         Length:109         Min.   :0.00   Min.   :0.800  
##  Class :character   Class :character   1st Qu.:3.20   1st Qu.:4.000  
##  Mode  :character   Mode  :character   Median :4.80   Median :5.600  
##                                        Mean   :4.48   Mean   :5.503  
##                                        3rd Qu.:5.70   3rd Qu.:6.800  
##                                        Max.   :8.30   Max.   :9.600  
##                                                                      
##  Schriftelijk.Voldoende Schriftelijk.Bonus Schriftelijk.Bonus.Voldoende
##  Min.   :  0.00         Min.   : 0.800     Min.   :  0.00              
##  1st Qu.:  0.00         1st Qu.: 4.000     1st Qu.:  0.00              
##  Median :100.00         Median : 5.600     Median :100.00              
##  Mean   : 52.29         Mean   : 5.787     Mean   : 53.21              
##  3rd Qu.:100.00         3rd Qu.: 7.600     3rd Qu.:100.00              
##  Max.   :100.00         Max.   :10.000     Max.   :100.00              
##                                                                        
##      Clicks        Weblectures     BEC.Propedeuse  AEC.Propedeuse  
##  Min.   :   1.0   Min.   :0.0000   Min.   :0.000   Min.   :0.0000  
##  1st Qu.: 269.0   1st Qu.:0.0000   1st Qu.:1.000   1st Qu.:1.0000  
##  Median : 386.0   Median :0.0000   Median :1.000   Median :1.0000  
##  Mean   : 445.7   Mean   :0.8505   Mean   :0.875   Mean   :0.9327  
##  3rd Qu.: 541.0   3rd Qu.:1.2000   3rd Qu.:1.000   3rd Qu.:1.0000  
##  Max.   :1058.0   Max.   :6.8000   Max.   :1.000   Max.   :1.0000  
##                                    NA&#39;s   :5       NA&#39;s   :5       
##  Vooropleiding     
##  Length:109        
##  Class :character  
##  Mode  :character  
##                    
##                    
##                    
## </code></pre>
<p><br> We kunnen hieruit onder andere aflezen dat de gemiddelde score van de kennistoetsen 4.48 bedroeg met een maximum van 8.3 en dat bij de variabele <code>BEC.Propedeuse</code> van 5 observaties de gegevens ontbreken (<code>NA</code>).</p>
<p>Door in het <em>Environment</em> veld op de variabele <code>StudDF</code> te klikken (of in de <em>Console</em> met het commando <code>View(studDF)</code>), krijg je een tabel met alle data.</p>
<div class="figure">
<img src="images/view.png" alt="" />

</div>
<div id="vragenset-1a" class="section level3">
<h3>Vragenset 1A</h3>
<ol style="list-style-type: decimal">
<li><p>Hoeveel procent van de studenten heeft voor het schriftelijk tentamen (inclusief bonuspunten) een voldoende gehaald?</p></li>
<li><p>In hoeveel procent van de gevallen hadden studenten de bonuspunten nodig om voor het schriftelijk een voldoende te halen?</p></li>
</ol>
</div>
</div>
<div id="online-bestand" class="section level2">
<h2>Online bestand</h2>
<p>We kunnen met R ook heel makkelijk data ophalen die online is opgeslagen. In dit voorbeeld lezen we data uit een Google Spreadsheet uit. Er zijn verschillende packages die voor deze taak geschikt zijn. Wij gaan de package <code>gsheet</code> gebruiken.</p>
<pre class="r"><code>## Laad de benodigde package(s)
library(gsheet)

## Lees online data in
url &lt;- &quot;https://docs.google.com/spreadsheets/d/1YnAdYzJ6hAHlFTbgv2xMxkMwGyAcFM8zM1FMnEkJKgw&quot;
surveyDF &lt;- gsheet2tbl(url)</code></pre>
<div id="vragenset-1b" class="section level3">
<h3>Vragenset 1B</h3>
<ol style="list-style-type: decimal">
<li><p>Om wat voor een soort data gaat het hier?</p></li>
<li><p>Welke dimensies heeft de dataset (rijen / kolommen)?</p></li>
<li><p>Welke classes hebben de variabelen?</p></li>
<li><p>Wat is het gemiddelde niveau van de ingeschatte vaardigheden?</p></li>
</ol>
</div>
</div>
<div id="web-scraping" class="section level2">
<h2>Web scraping</h2>
<p>Een andere wijze om online data te verzamelen is via <em>web scraping</em>. Soms zie je op webpagina’s tabellen met data staan, zoals bijvoorbeeld <a href="http://www.pginvestor.com/Historic-Prices">hier</a>. Met de <code>rvest</code> package kunnen we de data uit de html code filteren.</p>
<pre class="r"><code># Laad de benodigde package(s)
library(rvest)

# Lees ruwe html data in.
htmlpage &lt;- read_html(&quot;http://www.pginvestor.com/Historic-Prices&quot;)

# Extraheer alle tabellen uit de ruwe data
nodes &lt;- html_nodes(htmlpage, &quot;table&quot;)
tables &lt;- html_table(nodes, fill = TRUE)

# Kies een tabel en stop de data in een data frame
stockDF &lt;- tables[1][[1]]</code></pre>
<div id="vragenset-1c" class="section level3">
<h3>Vragenset 1C</h3>
<ol style="list-style-type: decimal">
<li><p>Wat voor een soort data bevat <code>stockDF</code>?</p></li>
<li><p>Welke classes hebben de variabelen?</p></li>
<li><p>Wat was de hoogste waarde voor de variabele<code>Price</code>?</p></li>
</ol>
</div>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
$(document).ready(function () {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
});

</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
